// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeWz3ZxSKUBBwa1ySEepoHZG9IIeeFTTU',
    appId: '1:137416597415:web:f33398e2ba0cac1512e082',
    messagingSenderId: '137416597415',
    projectId: 'crud-3b201',
    authDomain: 'crud-3b201.firebaseapp.com',
    storageBucket: 'crud-3b201.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfo3xIAhXVLJABoSlDn9-HPRBPLqro5QA',
    appId: '1:137416597415:android:8b7a1f1c5194287a12e082',
    messagingSenderId: '137416597415',
    projectId: 'crud-3b201',
    storageBucket: 'crud-3b201.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPMWNj9sFfRPlr_G4ABERcjqZ2FsYLslY',
    appId: '1:137416597415:ios:6edfcee6f886de2912e082',
    messagingSenderId: '137416597415',
    projectId: 'crud-3b201',
    storageBucket: 'crud-3b201.appspot.com',
    iosBundleId: 'com.roshan.firebase.crud.firebaseCrud',
  );
}
